server.port: 8081

spring:
  application.name: ichiro-family-tree-viewer
  config.import: optional:file:.env[.properties] # enable scanning of .env file for environment variables

family-tree.api:
  url: http://138.2.178.94:8080
  key: ${IFT_API_KEY}