spring:
  application.name: ichiro-family-tree-viewer
  config.import: optional:file:.env[.properties] # enable scanning of .env file for environment variables
server.port: 5000 # Elastic Beanstalk port

family-tree.api:
  url: http://ichirofamilytreeapi-env.eba-gaw6w87q.eu-central-1.elasticbeanstalk.com
  key: ${FAMILY_TREE_API_KEY}