name: Build and Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build and create production package
      run: mvn -B clean package -Dvaadin.productionMode=true